set( CMAKE_SYSTEM_NAME Linux )
set( CMAKE_C_COMPILER  "/Users/hansklabbers/Dev/IoT/edison_media/iss-iot-mac/devkit-x86/sysroots/i386-pokysdk-darwin/usr/bin/i586-poky-linux/i586-poky-linux-gcc" )
set( CMAKE_CXX_COMPILER "/Users/hansklabbers/Dev/IoT/edison_media/iss-iot-mac/devkit-x86/sysroots/i386-pokysdk-darwin/usr/bin/i586-poky-linux/i586-poky-linux-g++" )
set( CMAKE_SYSTEM_PROCESSOR core2-32-poky-linux )
set( CMAKE_CXX_FLAGS  "--sysroot=/Users/hansklabbers/Dev/IoT/edison_media/iss-iot-mac/devkit-x86/sysroots/i586-poky-linux -O2 -pipe -g -feliminate-unused-debug-types" CACHE STRING "" FORCE )
#set( CMAKE_C_FLAGS ${CMAKE_CXX_FLAGS} CACHE STRING "" FORCE ) #same flags for C sources
set( CMAKE_EXE_LINKER_FLAGS --sysroot=/Users/hansklabbers/Dev/IoT/edison_media/iss-iot-mac/devkit-x86/sysroots/i586-poky-linux CACHE STRING "" FORCE )
#set( CMAKE_LDFLAGS_FLAGS --sysroot=/Users/hansklabbers/Dev/IoT/edison_media/iss-iot-mac/devkit-x86/sysroots/i586-poky-linux CACHE STRING "" FORCE )
set( CMAKE_LIBRARY_PATH ~/Dev/IoT/edison_media/iss-iot-mac/devkit-x86/sysroots/i586-poky-linux/usr/lib )
set( CMAKE_FIND_ROOT_PATH ~/Dev/IoT/edison_media/iss-iot-mac/devkit-x86/sysroots/i586-poky-linux
  	~/Dev/IoT/edison_media/iss-iot-mac/devkit-x86/sysroots/i386-pokysdk-darwin )
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
#set( AS i586-poky-linux-as )
#set( LD i586-poky-linux-ld   --sysroot=/opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux )
#set( GDB i586-poky-linux-gdb )
#set( STRIP i586-poky-linux-strip )
#set( RANLIB i586-poky-linux-ranlib )
#set( OBJCOPY i586-poky-linux-objcopy )
#set( OBJDUMP i586-poky-linux-objdump )
#set( AR i586-poky-linux-ar )
#set( NM i586-poky-linux-nm )
#set( M4 m4 )
#set( TARGET_PREFIX i586-poky-linux- )
#set( CONFIGURE_FLAGS --target=i586-poky-linux --host=i586-poky-linux --build=i386-linux --with-libtool-sysroot=/opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux )
#set( BUILDARCH x86 )
#set( CROSS_COMPILE i586-poky-linux- )
